[package]
name = "simple_image_handler"
version = "0.1.0"
edition = "2021"
authors = ["RysteQ"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"